seed_everything: 15
trainer:
  accelerator: auto
  strategy: auto
    # class_path: DDPStrategy
    # init_args:
    #   process_group_backend: gloo
  devices: 1
  num_nodes: 1
  precision: 16
  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: './'
      name: dino_test
      # name: pretraining-resnet
      prefix: ''
      version: 'sd198-bs256-in21k-fp16-do03-lr1e5'
      default_hp_metric: false
      log_graph: true
    dict_kwargs:
      max_queue: 10
  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        monitor: 'val/loss'
        save_top_k: 1
        mode: 'min'
        auto_insert_metric_name: false
        save_last: true
        filename: 'epoch={epoch}-val_loss={val/loss:.4f}'
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
    - class_path: TQDMProgressBar
      init_args:
        refresh_rate: 100
  max_epochs: -1
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: false
model:
  class_path: model.DINO_Model
  init_args:
    vit_type: dino_vitb16
    learning_rate: 1e-5
    weight_decay: 1e-2
    loss_temperature: 0.05
data:
  # dataset_name: sd-198
  # dataset_name: fitspatrick-17k
  # dataset_name: comb
  dataset_name: isic
  batch_size: 64
  resolution: 224
  self_supervised: true
  transforms:
    class_path: lightly.transforms.dino_transform.DINOTransform
ckpt_path: null